import Foundation
import Testing
@testable import notetaker

@Suite("MeetingRecapFormatter")
struct MeetingRecapFormatterTests {
    @Test func formatSubjectWithTitle() {
        let subject = MeetingRecapFormatter.formatSubject(title: "Sprint Planning", date: Date())
        #expect(subject.contains("Sprint Planning"))
        #expect(subject.contains("Meeting Recap"))
    }

    @Test func formatSubjectWithEmptyTitle() {
        let subject = MeetingRecapFormatter.formatSubject(title: "", date: Date())
        #expect(subject.contains("Untitled Recording"))
    }

    @Test func formatBodyIncludesSummary() {
        let data = MeetingRecapFormatter.RecapData(
            title: "Test Meeting",
            date: Date(),
            duration: 3600,
            overallSummary: "We discussed important topics.",
            chunkSummaries: [],
            transcriptExcerpt: nil
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("We discussed important topics"))
        #expect(body.contains("Test Meeting"))
        #expect(body.contains("60m"))
    }

    @Test func formatBodyIncludesChunkSummaries() {
        let data = MeetingRecapFormatter.RecapData(
            title: "Test",
            date: Date(),
            duration: 600,
            overallSummary: nil,
            chunkSummaries: [(from: 0, to: 300, content: "First half discussion"), (from: 300, to: 600, content: "Second half")],
            transcriptExcerpt: nil
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("First half discussion"))
        #expect(body.contains("0:00"))
        #expect(body.contains("5:00"))
    }

    @Test func formatBodyIncludesTranscriptExcerpt() {
        let data = MeetingRecapFormatter.RecapData(
            title: "Test",
            date: Date(),
            duration: 60,
            overallSummary: nil,
            chunkSummaries: [],
            transcriptExcerpt: "Hello everyone, welcome to the meeting."
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("Hello everyone"))
        #expect(body.contains("Transcript Excerpt"))
    }

    @Test func formatBodyWithEmptyData() {
        let data = MeetingRecapFormatter.RecapData(
            title: "",
            date: Date(),
            duration: 0,
            overallSummary: nil,
            chunkSummaries: [],
            transcriptExcerpt: nil
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("Untitled Recording"))
        #expect(body.contains("Generated by Notetaker"))
    }

    @Test func mailtoURLBasic() {
        let url = MeetingRecapFormatter.mailtoURL(to: ["test@example.com"], subject: "Test", body: "Hello")
        #expect(url != nil)
        let urlStr = url!.absoluteString
        #expect(urlStr.contains("mailto:"))
        #expect(urlStr.contains("test@example.com"))
    }

    @Test func mailtoURLNoRecipients() {
        let url = MeetingRecapFormatter.mailtoURL(to: [], subject: "Test", body: "Hello")
        #expect(url != nil)
    }

    @Test func mailtoURLEncodesSpecialChars() {
        let url = MeetingRecapFormatter.mailtoURL(to: [], subject: "Hello & Goodbye", body: "Line 1\nLine 2")
        #expect(url != nil)
    }

    @Test func formatDurationMinutesAndSeconds() {
        let data = MeetingRecapFormatter.RecapData(
            title: "Test",
            date: Date(),
            duration: 125,
            overallSummary: nil,
            chunkSummaries: [],
            transcriptExcerpt: nil
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("2m 5s"))
    }

    @Test func formatBodyFooter() {
        let data = MeetingRecapFormatter.RecapData(
            title: "Test",
            date: Date(),
            duration: 60,
            overallSummary: "Summary",
            chunkSummaries: [],
            transcriptExcerpt: nil
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("---"))
        #expect(body.contains("Generated by Notetaker"))
    }

    @Test func formatTimeHelper() {
        let data = MeetingRecapFormatter.RecapData(
            title: "Test",
            date: Date(),
            duration: 7200,
            overallSummary: nil,
            chunkSummaries: [(from: 3661, to: 3720, content: "Late discussion")],
            transcriptExcerpt: nil
        )
        let body = MeetingRecapFormatter.formatBody(from: data)
        #expect(body.contains("61:01"))
    }

    @Test func multipleRecipients() {
        let url = MeetingRecapFormatter.mailtoURL(to: ["a@b.com", "c@d.com"], subject: "Test", body: "Hi")
        #expect(url != nil)
        let urlStr = url!.absoluteString
        #expect(urlStr.contains("a@b.com"))
    }
}
