import SwiftUI

/// Beautiful summary card template for image export.
/// Not displayed in app UI — used only for ImageRenderer rendering.
struct SummaryCardTemplate: View {
    let data: SummaryCardData

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Header
            VStack(alignment: .leading, spacing: 8) {
                Text(data.title)
                    .font(.system(size: 22, weight: .bold))
                    .foregroundStyle(titleColor)

                HStack(spacing: 12) {
                    Label(data.date.formatted(date: .abbreviated, time: .shortened),
                          systemImage: "calendar")
                    Label(SummaryCardExporter.formatDuration(data.duration),
                          systemImage: "clock")
                }
                .font(.system(size: 13))
                .foregroundStyle(subtitleColor)
            }

            Divider()
                .overlay(dividerColor)

            // Bullet points (if extracted)
            if !data.bulletPoints.isEmpty {
                VStack(alignment: .leading, spacing: 8) {
                    ForEach(Array(data.bulletPoints.prefix(8).enumerated()), id: \.offset) { _, point in
                        HStack(alignment: .top, spacing: 8) {
                            Image(systemName: "checkmark.circle.fill")
                                .foregroundStyle(.green)
                                .font(.system(size: 14))
                            Text(point)
                                .font(.system(size: 14))
                                .foregroundStyle(textColor)
                        }
                    }
                }
            } else {
                // Plain summary text
                Text(data.summaryText)
                    .font(.system(size: 14))
                    .foregroundStyle(textColor)
                    .lineLimit(12)
            }

            Spacer(minLength: 8)

            // Footer
            HStack {
                Spacer()
                Text("Generated by Notetaker")
                    .font(.system(size: 11))
                    .foregroundStyle(footerColor)
            }
        }
        .padding(24)
        .frame(width: 600)
        .background(backgroundView)
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }

    // MARK: - Style Colors

    private var titleColor: Color {
        switch data.style {
        case .light: .primary
        case .dark: .white
        case .gradient: .white
        }
    }

    private var subtitleColor: Color {
        switch data.style {
        case .light: .secondary
        case .dark: .white.opacity(0.7)
        case .gradient: .white.opacity(0.8)
        }
    }

    private var textColor: Color {
        switch data.style {
        case .light: .primary
        case .dark: .white.opacity(0.9)
        case .gradient: .white.opacity(0.95)
        }
    }

    private var dividerColor: Color {
        switch data.style {
        case .light: .gray.opacity(0.3)
        case .dark: .white.opacity(0.2)
        case .gradient: .white.opacity(0.3)
        }
    }

    private var footerColor: Color {
        switch data.style {
        case .light: .gray
        case .dark: .white.opacity(0.4)
        case .gradient: .white.opacity(0.5)
        }
    }

    @ViewBuilder
    private var backgroundView: some View {
        switch data.style {
        case .light:
            Color.white
        case .dark:
            Color(nsColor: NSColor(red: 0.12, green: 0.12, blue: 0.14, alpha: 1.0))
        case .gradient:
            LinearGradient(
                colors: [
                    Color(red: 0.1, green: 0.2, blue: 0.5),
                    Color(red: 0.3, green: 0.1, blue: 0.5)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
        }
    }
}
