import Foundation
import os

/// Formats meeting recap emails from session data.
nonisolated enum MeetingRecapFormatter {
    private static let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "notetaker", category: "MeetingRecapFormatter")

    /// Lightweight data carrier for recap generation (avoids SwiftData isolation issues).
    struct RecapData: Sendable {
        let title: String
        let date: Date
        let duration: TimeInterval
        let overallSummary: String?
        let chunkSummaries: [(from: TimeInterval, to: TimeInterval, content: String)]
        let transcriptExcerpt: String?
    }

    /// Format email subject line.
    static func formatSubject(title: String, date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        let dateStr = formatter.string(from: date)
        let displayTitle = title.isEmpty ? "Untitled Recording" : title
        return "Meeting Recap — \(displayTitle) (\(dateStr))"
    }

    /// Format the full recap body in Markdown.
    static func formatBody(from data: RecapData) -> String {
        var lines = [String]()

        let displayTitle = data.title.isEmpty ? "Untitled Recording" : data.title
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        formatter.timeStyle = .short
        let dateStr = formatter.string(from: data.date)

        lines.append("Hi team,")
        lines.append("")
        lines.append("Here is the recap for **\(displayTitle)** on \(dateStr):")
        lines.append("")

        let minutes = Int(data.duration) / 60
        let seconds = Int(data.duration) % 60
        lines.append("**Duration:** \(minutes)m \(seconds)s")
        lines.append("")

        if let overall = data.overallSummary, !overall.isEmpty {
            lines.append("## Summary")
            lines.append(overall)
            lines.append("")
        }

        if !data.chunkSummaries.isEmpty {
            lines.append("## Key Points by Time")
            for chunk in data.chunkSummaries {
                let fromStr = formatTime(chunk.from)
                let toStr = formatTime(chunk.to)
                lines.append("**\(fromStr)–\(toStr):** \(chunk.content)")
            }
            lines.append("")
        }

        if let excerpt = data.transcriptExcerpt, !excerpt.isEmpty {
            lines.append("## Transcript Excerpt")
            lines.append(excerpt)
            lines.append("")
        }

        lines.append("---")
        lines.append("*Generated by Notetaker*")

        return lines.joined(separator: "\n")
    }

    /// Build a mailto: URL that opens the default mail client.
    static func mailtoURL(to recipients: [String] = [], subject: String, body: String) -> URL? {
        var components = URLComponents()
        components.scheme = "mailto"
        components.path = recipients.joined(separator: ",")

        var queryItems = [URLQueryItem]()
        queryItems.append(URLQueryItem(name: "subject", value: subject))
        queryItems.append(URLQueryItem(name: "body", value: body))
        components.queryItems = queryItems

        return components.url
    }

    /// Build RecapData from a RecordingSession (call on MainActor since RecordingSession is SwiftData).
    static func recapData(from session: RecordingSession) -> RecapData {
        let segments = session.segments.sorted { $0.startTime < $1.startTime }
        let summaries = session.summaries.sorted { $0.coveringFrom < $1.coveringFrom }

        let overallSummary = summaries.first(where: { $0.isOverall })?.displayContent
        let chunkSummaries = summaries
            .filter { !$0.isOverall }
            .map { (from: $0.coveringFrom, to: $0.coveringTo, content: $0.displayContent) }

        let fullText = segments.map(\.text).joined(separator: " ")
        let excerpt = fullText.isEmpty ? nil : String(fullText.prefix(500))

        let duration = session.totalDuration

        return RecapData(
            title: session.title,
            date: session.startedAt,
            duration: duration,
            overallSummary: overallSummary,
            chunkSummaries: chunkSummaries,
            transcriptExcerpt: excerpt
        )
    }

    // MARK: - Helpers

    private static func formatTime(_ seconds: TimeInterval) -> String {
        let mins = Int(seconds) / 60
        let secs = Int(seconds) % 60
        return String(format: "%d:%02d", mins, secs)
    }
}
